# Generated by Django 5.1.5 on 2025-03-10 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='aktif', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('kd_mk', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_mk', models.CharField(max_length=100)),
                ('sks', models.IntegerField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('sks__gt', 1)), name='sks_lebih_dari_2')],
            },
        ),
        migrations.CreateModel(
            name='Belajar',
            fields=[
                ('kd_belajar', models.AutoField(primary_key=True, serialize=False)),
                ('kd_mhs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='piggypoggo_app.mahasiswa')),
                ('kd_mkuliah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='piggypoggo_app.matakuliah')),
            ],
        ),
    ]
