# Generated by Django 5.1.5 on 2025-04-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0003_remove_belajar_kd_mhs_remove_belajar_kd_mkuliah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kandang', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
