# Generated by Django 5.1.5 on 2025-05-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0005_babi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babi',
            old_name='nomor_kandang',
            new_name='kandang',
        ),
    ]
