# Generated by Django 5.1.5 on 2025-05-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0006_rename_nomor_kandang_babi_kandang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riwayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riwayat', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
