# Generated by Django 5.1.5 on 2025-05-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0007_riwayat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipe', models.CharField(blank=True, choices=[('1', 'Harian'), ('2', 'Mingguan'), ('3', 'Bulanan')], max_length=10, null=True)),
                ('last_reset', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
