# Generated by Django 5.1.5 on 2025-05-26 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0008_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
                ('berat_badan', models.IntegerField()),
                ('obat', models.BooleanField(default=False)),
                ('babi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piggypoggo_app.babi')),
            ],
        ),
    ]
