# Generated by Django 5.1.5 on 2025-05-26 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0009_laporan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('babi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piggypoggo_app.babi')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piggypoggo_app.nota')),
            ],
        ),
    ]
