# Generated by Django 5.1.5 on 2025-05-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0010_nota_detailnota'),
    ]

    operations = [
        migrations.AddField(
            model_name='babi',
            name='terjual',
            field=models.BooleanField(default=False),
        ),
    ]
