# Generated by Django 5.1.5 on 2025-05-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0011_babi_terjual'),
    ]

    operations = [
        migrations.AddField(
            model_name='babi',
            name='harga',
            field=models.IntegerField(default=0),
        ),
    ]
