# Generated by Django 5.1.5 on 2025-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0012_babi_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='babi',
            name='sakit',
            field=models.BooleanField(default=False),
        ),
    ]
