# Generated by Django 5.1.5 on 2025-05-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0013_babi_sakit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='nama_pembeli',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
