# Generated by Django 5.1.5 on 2025-05-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0014_nota_nama_pembeli'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='kode_nota',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
