# Generated by Django 5.1.5 on 2025-05-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0015_nota_kode_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='tanggal',
            new_name='tanggal_nota',
        ),
        migrations.AddField(
            model_name='nota',
            name='tanggal_dibeli',
            field=models.DateField(blank=True, null=True),
        ),
    ]
