# Generated by Django 5.1.5 on 2025-05-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0018_alter_detailnota_babi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailnota',
            name='babi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='piggypoggo_app.babi'),
        ),
    ]
