# Generated by Django 5.1.5 on 2025-06-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0019_alter_detailnota_babi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailnota',
            name='babi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piggypoggo_app.babi'),
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piggypoggo_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DailyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_daily', models.CharField(blank=True, max_length=50, null=True)),
                ('daily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piggypoggo_app.daily')),
            ],
        ),
    ]
