# Generated by Django 5.1.5 on 2025-06-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0020_alter_detailnota_babi_daily_dailydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydetail',
            name='last_check',
            field=models.DateField(auto_now=True),
        ),
    ]
