# Generated by Django 5.1.5 on 2025-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0021_dailydetail_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='last_check',
            field=models.DateField(),
        ),
    ]
