# Generated by Django 5.1.5 on 2025-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0022_alter_dailydetail_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='berat_badan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
