# Generated by Django 5.1.5 on 2025-06-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0023_alter_laporan_berat_badan'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='foto_babi',
            field=models.ImageField(blank=True, null=True, upload_to='foto_babi/'),
        ),
    ]
