# Generated by Django 5.2.3 on 2025-06-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0024_laporan_foto_babi'),
    ]

    operations = [
        migrations.AddField(
            model_name='babi',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
