# Generated by Django 5.1.5 on 2025-06-16 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0025_babi_tanggal_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayat',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piggypoggo_app.userprofile'),
        ),
    ]
