# Generated by Django 5.2.3 on 2025-06-23 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0026_riwayat_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailnota',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_nota', to='piggypoggo_app.nota'),
        ),
    ]
