# Generated by Django 5.2.3 on 2025-06-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0027_alter_detailnota_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='pengurangan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
