# Generated by Django 5.2.3 on 2025-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0028_nota_pengurangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='pengiriman',
            field=models.CharField(choices=[('Dikirim', 'Dikirim'), ('Ditempat', 'Ditempat')], default='Ditempat'),
        ),
    ]
