# Generated by Django 5.1.5 on 2025-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggypoggo_app', '0029_nota_alamat_nota_pengiriman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='pengiriman',
            field=models.CharField(choices=[('Dikirim', 'Dikirim'), ('Ditempat', 'Ditempat')], default='Ditempat', max_length=10),
        ),
    ]
